### PR TITLE
Add TopFrame function

### PR DESCRIPTION
**Pull request by kazukousen**
Support to add `TopFrame` function

### CODE REVIEW

**Review by winebarrel — APPROVED** [review]
👍

**Comment by kazukousen** [comment]
@winebarrel 

PTAL 🙇 [88cf9b3](https://github.com/kanmu/pperr/pull/10/commits/88cf9b3a9d959597c12a3ef5404a09f84d773355)

**Comment by kazukousen** [comment]
@winebarrel PTAL again 🙇 0073343

**Review by winebarrel — APPROVED** [review]
LGTM!

**Pull request merged**
